---
title: "Temas por Charlar"
subtitle: "Asunto: varios"
author: "Alexys H. Rodr칤guez-Avellaneda Ph.D."
format:
  revealjs:
    theme: simple
    slide-number: true
    transition: fade
    incremental: true
    center: true
---

## Enfoque Open Science

- Material presentado por profesor
    - Diapositivas
    - C칩digo
    - Teor칤a
    - Archivos de configuraci칩n
- Material de los estudiantes
- HTML, PDF
- GitHub

游뛂 Evitar guardar su trabajo en los discos duros.

---

## Clase de Hoy: Instalaci칩n y uso b치sico de Herramientas


- 1. Contenedores Docker
- 2. VSCode
- 3. Git
- 4. Docker Desktop
- 5. Jupyter Lab
- 6. VSCode
- 7. Archivos Quarto: HTML & PDF
- 8. QGIS 1 (instalaci칩n)
- 9. QGIS 2 (instalaci칩n)
- 10. Chequeo ArcGIS Pro


---


## Contenido - Syllabus (Semana 2)

Parte 1: **Fundamentos **

Teor칤a:

- 1. Avances y Tendencias de la Geom치tica

Ejercicios:

- Acceder a Geoportales y Bases de Datos

Trabajo Independiente:

- Lectura: Cap칤tulo 1: Geomatics.(Gomarasca, 2009)


---

## Contenido - Syllabus (Semana 3 y 4)

Parte 1: **Fundamentos **

Teor칤a:

- 2. Fundamentos Geod칠sicos y Cartogr치ficos
    - Elipsoide, geoide, datum, sistemas de coordenadas, escala, tipos de mapas, exactitud y precisi칩n

Ejercicios:

- Establecer los diferentes or칤genes para Colombia y origen 칰nico nacional
- Determinar escala de una fotograf칤a a칠rea.

---

## Contenido - Syllabus (Semana 3 y 4)

Parte 1: **Fundamentos **

Trabajo Independiente:

- Exploraci칩n portales web de proyecciones cartogr치ficas.
    - Map-Project (Jung, 2023).
    - The True Size (Talmage & Maneice, 2023)
- Lectura: 
    - Escala (Demmatt칡 et al., 2002; Jo칚o, 2002; Poggio, Gimona, & Brewer, 2013)
    - Sistemas de Referencia (Islas & Angelo, 2000)
    - Cartograf칤a. (Anthamatten, 2020)

---


## Contenido - Syllabus (Semana 5 y 6: **SIG**)

Parte 2: **Estructuras de Datos Espaciales**

Teor칤a:

- 3. Estructura de los datos e informaci칩n espacial
- 4. Modelo de datos Vector
- 5. Modelo de datos Raster
- 6. Operaciones de los modelos de datos

---

## Contenido - Syllabus (Semana 5 y 6: **SIG**)

Parte 2: **Estructuras de Datos Espaciales**

Ejercicios:

- B칰squeda y descarga de modelos de datos (Vector y Raster).
- Captura de informaci칩n (GDB o GeoPackage).

Trabajo Independiente:

- Captura de informaci칩n de una zona de inter칠s.
- Presentar propuesta de **trabajo final**
- Libros Gu칤a SIG (Longley et al., 2011; Shellito, 2020; Wise, 2014)

---

## Contenido - Syllabus (Semana 7 a 9: **Sensores Remotos**)

Parte 2: **Estructuras de Datos Espaciales**

Teor칤a:

- 7. 쯈u칠 es percepci칩n remota?.
- 8. Componentes.
- 9. Ventajas y limitaciones.
- 10. Caracter칤sticas de las im치genes.
- 11. Fases del proceso de interpretaci칩n.
- 12. Correcciones.
- 13. Nivel de referencia.
- 14. Reglas y m칠todos de interpretaci칩n.
- 15. 쮺칩mo se identifican los objetos? 

---

## Contenido - Syllabus (Semana 7 a 9: **Sensores Remotos**)

Parte 2: **Estructuras de Datos Espaciales**


Ejercicios:

- Revisi칩n de Metadatos de productos de sensores remotos
- Introducci칩n a Google Earth Engine (GEE)
- Revisi칩n de Catalogo de datos de GEE
- Composici칩n de productos de sensores remotos
- C치lculo de 칤ndices de productos de sensores remotos
- Selecci칩n, recorte y descarga de im치genes de GEE
- An치lisis de datos Lidar

---

## Contenido - Syllabus (Semana 7 a 9: **Sensores Remotos**)

Parte 2: **Estructuras de Datos Espaciales**

Trabajo independiente:

- Exploraci칩n: QGIS y SNAP
- Libros Sensores Remotos 
    - Chuvieco, 2020; 
    - De Grandi & De Grandi, 2021; 
    - Dong & Chen, 2018; 
    - Campbell et al., 2022; 
    - Melo & Camacho, 2005

---

## Contenido - Syllabus (Semana 10: **Navegaci칩n Satelital**)

Parte 2: **Estructuras de Datos Espaciales**

Teor칤a:

- 16. 쯈u칠 es un sistema de navegaci칩n satelital?.
- 17. Tipos de sistemas de navegaci칩n satelital.
- 18. Tipos de levantamientos de informaci칩n.
- 19. Fuentes de error.

---

## Contenido - Syllabus (Semana 10: **Navegaci칩n Satelital**)

Parte 2: **Estructuras de Datos Espaciales**

Ejercicios:

- Creaci칩n de formularios para captura de informaci칩n de campo con sistemas de
navegaci칩n satelital.

Trabajo independiente:

- Crear un formulario (?)
- Libros sistemas de navegaci칩n: 
    - Borre et al., 2022; 
    - NovAtel , 2015; 
    - Ogaja, 2022

---

## Contenido - Syllabus (Semana 11: **Asesor칤a**)

Parte 2: **Estructuras de Datos Espaciales**

Teor칤a:
- ...

Ejercicios:
- ...

---

## Contenido - Syllabus (Semana 12 y 13: **MDE**)

Parte 2: **Estructuras de Datos Espaciales**

Teor칤a:

- 20. 쯈u칠 es un Modelo Digital de Elevaci칩n (MDE)?.
- 21. Creaci칩n.
- 22. Par치metros derivados.
- 23. Aplicaciones.

---

## Contenido - Syllabus (Semana 12 y 13: **MDE**)

Parte 2: **Estructuras de Datos Espaciales**

Ejercicios pr치cticos:

- Creaci칩n.
- Comparaci칩n de MDE (diferentes resoluciones).
- Derivar par치metros.
- Aplicaciones de los MDE.

Trabajo independiente:

- Lectura: Definiciones y conceptos de MDE. (Florinsky, 2012; Guth et al., 2021).

---

## Contenido - Syllabus (Semana 14: **Cartograf칤a Digital**)

Parte 3: **Presentaci칩n de la Informaci칩n Espacial**

Teor칤a:

- 24. Contexto espacial.
- 25. Elementos de la cartograf칤a.
- 26. Fuentes de entrada.
- 27. Edici칩n, estructuraci칩n y procesamiento.
- 28. Modelos del cat치logo de datos.
- 29. Dise침o de la cartograf칤a B치sica
- 30. Dise침o de la cartograf칤a Tem치tica
- 31. Generalizaci칩n
- 32. Metadatos - definici칩n.
- 33. Metadatos - estructuraci칩n.

---

## Contenido - Syllabus (Semana 14: **Cartograf칤a Digital**)

Parte 3: **Presentaci칩n de la Informaci칩n Espacial**

Ejercicios pr치cticos:

- Estructural un proyecto de cartograf칤a digital

Trabajo independiente:

- Lectura: Cartograf칤a digital
    - Kraak & Ormeling, 2021; 
    - Parker & Toms, 2022; 
    - Peterson, 2023;
    - Slocum et al., 2022

---

## Contenido - Syllabus (Semana 15 y 16: **Proyecto Final**)

Parte 4: **Aplicaciones de la Geom치tica**

T칩picos:

- 34. 쯇or qu칠 socializar los resultados de una investigaci칩n?

Ejercicios pr치cticos:

- Sustentaci칩n.

---

## Contenido - Syllabus (**Evaluaci칩n**)

- Talleres te칩rico-pr치cticos (60%)
- Trabajo final (40%)

## Contenido - Syllabus (**Metodolog칤a**)

- 1. Exposiciones del Profesor.
    - Teor칤a.
    - Pr치ctica.
- 2. Talleres.
- 3. Lecturas.
- 6. Trabajo Final.

游녤 Necesitamos concretarlo y asignar porcentajes espec칤ficos.

---

## Propuestas de Estudiantes para el Curso

游꿢 Tienes la palabra.

---

## Temas para Proyecto Final

- 1. ...
- 2. ...

---

## Paquetes o comandos faltantes en Dockerfile

- `apt-get update && apt-get install -y fonts-symbola`
- Julia: `FileIO`, `ImageIO`

---
